version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  open-pull-requests-limit: 10
  reviewers:
      - dhruvmanila
      - cdrini
  schedule:
    interval: weekly
    day: sunday
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
 
