default_language_version:
  python: python3.8
default_stages: [push]
repos:
  - repo: local
    hooks:
      - id: make-lint-diff
        name: make lint-diff
        # Running git inside docker is slow for some reason, so do that outside and pipe
        # the results into docker.
        entry: git diff master -U0 | docker-compose run --rm web ./scripts/flake8-diff.sh
        language: script
