default_language_version:
  python: python3.8
default_stages: [push]
repos:
  - repo: local
    hooks:
      - id: make-lint-diff
        name: make lint-diff
        entry: docker-compose run --rm web make lint-diff
        language: script
      # The following hook works but takes several seconds...
      #- id: make-lint
      #  name: make lint
      #  entry: /usr/bin/make lint
      #  language: script
