dist: bionic
language: python
addons:
  apt:
    packages:
      - libgeoip-dev
matrix:
  include:
    - python: "2.7"
    - python: "3.7"
  allow_failures:
    - python: "3.7"
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  - npm install
script: make test
