os: linux
dist: bionic
language: python
jobs:
  include:
    - name: “Python 2.7 on xenial”
      python: "2.7"
      dist: xenial
    - name: “Python 2.7 on bionic”
      python: "2.7"
    - name: “Python 3.8 make lint and some pytests”
      python: "3.8"
      install: pip install flake8
      script:
        - make lint
        - pip install -r requirements_test.txt
        - pushd vendor/infogami && git pull origin master && popd
        - pytest openlibrary/mocks openlibrary/olbase openlibrary/utils scripts/tests
        # On pull requests, run all flake8 tests on modified code
        # if clause avoids `fatal: ambiguous argument 'origin/master'` on git push
        - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
            git diff origin/master -U0 | flake8 --diff --max-line-length=88;
          fi
    - name: “Python 3.8 on bionic”
      python: "3.8"
  allow_failures:
    - name: “Python 3.8 on bionic”
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  # if Travis is running Python 3, then
  #   refresh the git submodule ./vendor/infogami
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ]; then
      pushd vendor/infogami && git pull origin master && popd;
    fi
  - npm install
script:
  - make i18n
  - make test
