# Only run travis when pushing to master branch (and PRs)
branches:
  only:
    - master

os: linux
dist: focal
language: python
jobs:
  include:
    - name: Python 2.7 on xenial
      python: "2.7"
      dist: xenial
    - name: Python 2.7 on focal
      python: "2.7"
    - name: Python 2.7 on Infogami master
      python: "2.7"
      script:
        - make i18n
        - make test-py
        - pip install safety
        - safety check || true
    - name: Python 3.8 on focal
      python: "3.8"
    - name: Python 3.9 on focal
      python: "3.9"

    - name: Node
      language: node_js
      # Should match what's in our Dockerfile
      node_js: "12"
      install: npm install
      script:
        - npm run lint
        - make js
        - make css
        - make components
        - npm run test

  allow_failures:
    - name: Python 2.7 on Infogami master

install:
  - pip install --upgrade pip wheel
  - pip install -r requirements_test.txt
  # refresh the git submodule ./vendor/infogami on some jobs
  - if [ "$TRAVIS_PYTHON_VERSION" != "2.7" ] || [ "$TRAVIS_JOB_NAME" == "Python 2.7 on Infogami master" ]; then
      pushd vendor/infogami && git pull origin master && popd;
    fi
  - pip list --outdated

script:
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.9" ]; then
      make lint-diff;
    fi
  - make lint
  - make i18n
  - make test-py
  - source scripts/run_doctests.sh
