os: linux
dist: focal
language: python
jobs:
  include:
    - name: “Python 2.7 on xenial”
      python: "2.7"
      dist: xenial
    - name: “Python 2.7 on focal”
      python: "2.7"
    - name: “Python 2.7 on Infogami master”
      python: "2.7"
      script:
        - make i18n
        - make test
        - pip install safety
        - safety check || true
    - name: “Python 3.8 make lint and selected pytests”
      python: "3.8"
      before_script: true  # override npm install below
      script:
        # On pull requests, run all flake8 tests on modified code
        # if clause avoids `fatal: ambiguous argument 'origin/master'` on git push
        - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
            make lint-diff;
          fi
        - source scripts/run_doctests.sh
        - source scripts/test_py3.sh
    - name: “Python 3.8 on focal”
      python: "3.8"
  allow_failures:
    - name: “Python 2.7 on Infogami master”
    - name: “Python 3.8 on focal”
# Ubuntu may have an old version of node, so make sure Node 12 is installed
# and used instead. Should match Dockerfile.
before_install:
  - nvm install 12
  - nvm use 12
install:
  - pip install -r requirements_test.txt
  # refresh the git submodule ./vendor/infogami on some jobs
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ] || [ "$TRAVIS_JOB_NAME" == "Python 2.7 on Infogami master" ]; then
      pushd vendor/infogami && git pull origin master && popd;
    fi
before_script: npm install
script:
  - make lint
  - make i18n
  - make test
