os: linux
dist: bionic
language: python
jobs:
  include:
    - name: “Python 2.7 on xenial”
      python: "2.7"
      dist: xenial
    - name: “Python 2.7 on bionic”
      python: "2.7"
    - name: “Python 3.8 make lint and selected pytests”
      python: "3.8"
      before_script: true  # override npm install below
      script:
        - |
            pytest openlibrary/mocks openlibrary/olbase openlibrary/utils scripts/tests \
                openlibrary/coverstore/tests/test_code.py \
                openlibrary/coverstore/tests/test_webapp.py \
                openlibrary/plugins/admin/tests/test_services.py \
                openlibrary/plugins/importapi/tests/test_code_ils.py \
                openlibrary/plugins/importapi/tests/test_import_edition_builder.py \
                openlibrary/plugins/openlibrary/tests/test_borrow_home.py \
                openlibrary/plugins/openlibrary/tests/test_lists.py \
                openlibrary/plugins/upstream/tests/test_account.py \
                openlibrary/plugins/upstream/tests/test_addbook.py \
                openlibrary/plugins/upstream/tests/test_forms.py \
                openlibrary/plugins/upstream/tests/test_utils.py \
                openlibrary/plugins/worksearch/tests/test_worksearch.py \
                openlibrary/tests/core/test_helpers.py \
                openlibrary/tests/core/test_i18n.py \
                openlibrary/tests/core/test_init.py \
                openlibrary/tests/core/test_lending.py \
                openlibrary/tests/core/test_lists_engine.py \
                openlibrary/tests/core/test_models.py \
                openlibrary/tests/core/test_olmarkdown.py \
                openlibrary/tests/core/test_processors.py \
                openlibrary/tests/core/test_processors_invalidation.py \
                openlibrary/tests/core/test_ratings.py \
                openlibrary/tests/core/test_sponsors.py \
                openlibrary/tests/core/test_vendors.py \
                openlibrary/tests/core/test_waitinglist.py
                # Remove catalog tests as discussed in #3150
                # openlibrary/catalog/marc/tests/test_marc_binary.py \
                # openlibrary/catalog/marc/tests/test_marc_html.py \
                # openlibrary/catalog/merge/test_amazon.py \
                # openlibrary/catalog/merge/test_merge.py \
                # openlibrary/catalog/merge/test_merge_marc.py \
                # openlibrary/catalog/merge/test_names.py \
                # openlibrary/catalog/merge/test_normalize.py \
        # On pull requests, run all flake8 tests on modified code
        # if clause avoids `fatal: ambiguous argument 'origin/master'` on git push
        - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
            git diff origin/master -U0 | flake8 --diff --max-line-length=88;
          fi
    - name: “Python 3.8 on bionic”
      python: "3.8"
  allow_failures:
    - name: “Python 3.8 on bionic”
install:
  - pip install -r requirements_test.txt
  # if Travis is running Python 3, then
  #   refresh the git submodule ./vendor/infogami
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ]; then
      pushd vendor/infogami && git pull origin master && popd;
    fi
  - make lint  # TODO: Move this to script: section after #2951 lands
before_script: npm install
script:
  - make i18n
  - make test
