language: python
sudo: false
addons:
  apt:
    packages:
      - libgeoip-dev
      - python-lxml
      - python-yaml
python:
    - "2.7"
install:
  - pip install -r test_requirements.txt
  - npm install
script: make test
