language: python
dist: xenial
addons:
  apt:
    packages:
      - libgeoip-dev
python:
    - "2.7"
    - "3.6"
    - "3.7"
matrix:
  allow_failures:
    - python: "3.6"
    - python: "3.7"
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  - npm install
script: make test
