# Only run travis when pushing to master branch (and PRs)
branches:
  only:
    - master

os: linux
dist: xenial
language: python
jobs:
  include:
    - name: Python 2.7
      python: "2.7"

    - name: Python 2.7 on Infogami master
      python: "2.7"
      before_script:
        # Use infogami master
        - pushd vendor/infogami && git pull origin master && popd;

    - name: Python 3.8
      python: "3.8"
      before_script:
        # Use infogami master
        - pushd vendor/infogami && git pull origin master && popd;
        # Do more aggressive linting for newly added code
        - make lint-diff

    - name: Node
      language: node_js
      # Should match what's in our Dockerfile
      node_js: "12"
      install: npm install
      script:
        - npm run lint
        - make js
        - make css
        - make components
        - npm run test

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --use-feature=2020-resolver -r requirements_test.txt

script:
  - make lint
  - make i18n
  - make test-py
  - source scripts/run_doctests.sh
