dist: bionic
language: python
addons:
  apt:
    packages:
      - libgeoip-dev
matrix:
  include:
    - name: “Python 2.7 on xenial”
      python: "2.7"
      dist: xenial
    - name: “Python 2.7 on bionic”
      python: "2.7"
    - name: “Python 3.7 on bionic”
      python: "3.7"
  allow_failures:
    - python: "3.7"
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  - npm install
script: make test
