os: linux
dist: focal
language: python
jobs:
  include:
    - name: “Python 2.7.6 on xenial”
      python: "2.7.6"
      dist: xenial
    - name: “Python 2.7.6 on focal”
      python: "2.7.6"
    - name: “Python 3.8.3 make lint and selected pytests”
      python: "3.8.3"
      before_script: true  # override npm install below
      script:
        # On pull requests, run all flake8 tests on modified code
        # if clause avoids `fatal: ambiguous argument 'origin/master'` on git push
        - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
            make lint-diff;
          fi
        - source scripts/test-py3.sh
    - name: “Python 3.8.3 on focal”
      python: "3.8.3"
  allow_failures:
    - name: “Python 3.8.3 on focal”
# Ubuntu may have an old version of node, so make sure Node 12 is installed
# and used instead. Should match Dockerfile.
before_install:
  - nvm install 12
  - nvm use 12
install:
  - pip install -r requirements_test.txt
  # if Travis is running Python 3, then
  #   refresh the git submodule ./vendor/infogami
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8.3" ]; then
      pushd vendor/infogami && git pull origin master && popd;
    fi
  - make lint  # TODO: Move this to script: section after #2951 lands
before_script: npm install
script:
  - make i18n
  - make test
