# Only run travis when pushing to master branch (and PRs)
branches:
  only:
    - master

os: linux
dist: xenial
language: python
jobs:
  include:
    - name: Python 2.7
      python: "2.7"

    - name: Python 3.8
      python: "3.8"
      before_script:
        # Do more aggressive linting for newly added code
        - make lint-diff

    - name: Node
      language: node_js
      # Should match what's in our Dockerfile
      node_js: "12"
      install: npm install
      script:
        - npm run lint
        - make js
        - make css
        - make components
        - npm run test

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements_test.txt
  # Need to also test infogami-master
  - git clone https://github.com/internetarchive/infogami.git vendor/infogami-master
  # Remove symlink in favour of PYTHONPATH
  - rm infogami

script:
  - make lint
  - make i18n
  # Python 2 should also be tested against production infogami
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then
      PYTHONPATH="$PYTHONPATH:$PWD/vendor/infogami" make test-py;
      PYTHONPATH="$PYTHONPATH:$PWD/vendor/infogami" source scripts/run_doctests.sh;
    fi
  # Both should be tested against infogami-master
  - PYTHONPATH="$PYTHONPATH:$PWD/vendor/infogami-master" make test-py
  - PYTHONPATH="$PYTHONPATH:$PWD/vendor/infogami-master" source scripts/run_doctests.sh
