version: "3.1"
services:
  web:
    image: "oldev:${OLDEV_TAG:-latest}"
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - OL_CONFIG=${OL_CONFIG:-/openlibrary/conf/openlibrary.yml}
      - GUNICORN_OPTS=${GUNICORN_OPTS:- --reload --workers 4 --timeout 180}
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-web-start.sh
    ports:
      - ${WEB_PORT:-8080}:8080
    networks:
      - webnet
      - dbnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"

  solr:
    image: olsolr:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.olsolr
    restart: always
    environment:
      - ENV=${ENV:-dev}
    ports:
      - 8983:8983
    volumes:
      - solr-data:/var/lib/solr/data
    networks:
      - webnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"

  solr-updater:
    image: "oldev:${OLDEV_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-solr-updater-start.sh
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - OL_CONFIG=conf/openlibrary.yml
      - PYENV_VERSION=${PYENV_VERSION:-}
      - OL_URL=http://web:8080/
    volumes:
      - solr-updater-data:/solr-updater-data
    networks:
      - webnet
      - dbnet

  memcached:
    image: memcached
    networks:
      - webnet

  covers:
    image: "oldev:${OLDEV_TAG:-latest}"
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - COVERSTORE_CONFIG=${COVERSTORE_CONFIG:-/openlibrary/conf/coverstore.yml}
      - GUNICORN_OPTS=${GUNICORN_OPTS:- --reload --workers 1 --max-requests 250}
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-covers-start.sh
    expose:
      - 7075
    networks:
      - webnet
      - dbnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"

  infobase:
    image: "oldev:${OLDEV_TAG:-latest}"
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - INFOBASE_CONFIG=${INFOBASE_CONFIG:-/openlibrary/conf/infobase.yml}
      - INFOBASE_OPTS=${INFOBASE_OPTS:-}
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-infobase-start.sh
    expose:
      - 7000
    networks:
      - webnet
      - dbnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"

networks:
  webnet:
  dbnet:
volumes:
  solr-data:
  solr-updater-data:
