version: "3.1"
services:
  web:
    image: "${OLIMAGE:-oldev:latest}"
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - OL_CONFIG=${OL_CONFIG:-/openlibrary/conf/openlibrary.yml}
      - GUNICORN_OPTS=${GUNICORN_OPTS:- --reload --workers 4 --timeout 180}
    command: docker/ol-web-start.sh
    ports:
      - ${WEB_PORT:-8080}:8080
    networks:
      - webnet
      - dbnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"

  solr:
    image: solr:8.8.2
    expose:
      - 8983
    volumes:
      - solr-data:/var/solr/data
      - ./conf/solr8-ol:/opt/solr/server/solr/configsets/olconfig:ro
    networks:
      - webnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"
    # Create (or use if already existing) a core called "openlibrary" with our config & schema
    command: solr-precreate openlibrary /opt/solr/server/solr/configsets/olconfig

  solr-updater:
    image: "${OLIMAGE:-oldev:latest}"
    command: docker/ol-solr-updater-start.sh
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - OL_CONFIG=conf/openlibrary.yml
      - PYENV_VERSION=${PYENV_VERSION:-}
      - OL_URL=http://web:8080/
      - STATE_FILE=solr-update.offset
    volumes:
      - solr-updater-data:/solr-updater-data
    networks:
      - webnet
      - dbnet

  memcached:
    image: memcached
    networks:
      - webnet

  covers:
    image: "${OLIMAGE:-oldev:latest}"
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - COVERSTORE_CONFIG=${COVERSTORE_CONFIG:-/openlibrary/conf/coverstore.yml}
      - GUNICORN_OPTS=${GUNICORN_OPTS:- --reload --workers 1 --max-requests 250}
    command: docker/ol-covers-start.sh
    expose:
      - 7075
    networks:
      - webnet
      - dbnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"

  infobase:
    image: "${OLIMAGE:-oldev:latest}"
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - INFOBASE_CONFIG=${INFOBASE_CONFIG:-/openlibrary/conf/infobase.yml}
      - INFOBASE_OPTS=${INFOBASE_OPTS:-}
    command: docker/ol-infobase-start.sh
    expose:
      - 7000
    networks:
      - webnet
      - dbnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"

networks:
  webnet:
  dbnet:
volumes:
  solr-data:
  solr-updater-data:
