# This file is applied "on top" of docker-compose.yml when docker-compose
# is used without the -f parameter. It contains local development specific
# configuration options which we don't want to apply to production/staging

version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    ports:
      # Debugger
      - 3000:3000
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      # Persistent volume mount for generated css and js
      - ol-build:/openlibrary/static/build
      # Persistent volume mount for node_modules
      - ol-nodemodules:/openlibrary/node_modules
      # The above volume mounts are required so that the local dev bind mount below
      # does not clobber the data generated inside the image / container
      - .:/openlibrary
    depends_on:
      - db
      - infobase

  solr:
    ports:
      - 8983:8983

  solr-updater:
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary

  db:
    image: postgres:9.3
    networks:
      - dbnet
    volumes:
      - .:/openlibrary
      # Any files inside /docker-entrypoint-initdb.d/ will get run by postgres
      # if the db is empty (which as of now is always, since we don't store the
      # postgres data anywhere).
      - ./docker/ol-db-init.sh:/docker-entrypoint-initdb.d/ol-db-init.sh

  covers:
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    ports:
      - 7075:7075
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary

  infobase:
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    ports:
      - 7000:7000
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
    depends_on:
      - db

  home:
    image: "oldev:${OLDEV_TAG:-latest}"
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-home-start.sh
    networks:
      - webnet
      - dbnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"
    volumes:
      - ol-vendor:/openlibrary/vendor
      - ol-build:/openlibrary/static/build
      - ol-nodemodules:/openlibrary/node_modules
      - .:/openlibrary

volumes:
  ol-vendor:
  ol-build:
  ol-nodemodules:
