##
## Staging server config (wip)
## You probably want to run:
## export COMPOSE_FILE="docker-compose.yml:docker-compose.staging.yml"
## docker-compose up -d
##

version: "3.1"
services:
  web:
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - GUNICORN_OPTS= --workers 4 --timeout 180
      - OL_CONFIG=/olsystem/etc/openlibrary.yml
      - BEFORE_START=pip install -e /booklending_utils
    volumes:
      - ../olsystem:/olsystem
      - ../booklending_utils:/booklending_utils
      - ../olsystem/etc/ia.ini:/home/openlibrary/.config/ia.ini
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      # Persistent volume mount for generated css and js
      - ol-build:/openlibrary/static/build
      # Persistent volume mount for node_modules
      - ol-nodemodules:/openlibrary/node_modules
      # The above volume mounts are required so that the local dev bind mount below
      # does not clobber the data generated inside the image / container
      - .:/openlibrary
  solr-updater:
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
  db:
    volumes:
      - .:/openlibrary
  covers:
    ports:
      - 7075:7075
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
  infobase:
    ports:
      - 7000:7000
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
  home:
    volumes:
      - ol-vendor:/openlibrary/vendor
      - ol-build:/openlibrary/static/build
      - ol-nodemodules:/openlibrary/node_modules
      - .:/openlibrary
volumes:
  ol-vendor:
  ol-build:
  ol-nodemodules:

