##
## Production server config (wip)
## You probably want to run:
## docker-compose -f docker-compose.yml -f docker-compose.infogami-local.yml -f docker-compose.production.yml up -d
##

version: "3"
services:
  web:
    environment:
      - GUNICORN_OPTS= --workers 50 --timeout 300  # 5 minutes before reload
      - OL_CONFIG=/olsystem/etc/openlibrary.yml
      - PYENV_VERSION=3.8.6
    volumes:
      - ../olsystem:/olsystem
    command:
      - |
        ls -Fla /etc || true
        ls -Fla /olsystem || true
        ls -Fla /etc/nginx || true
        mkdir /etc/nginx || true
        ln -sfv /olsystem/etc/nginx/nginx.conf      /etc/nginx/nginx.conf
        ln -sfv /olsystem/etc/nginx/sites-available /etc/nginx/sites-available
        ls -Fla /etc/nginx || true
        systemctl start nginx
