##
## Production server config (wip)
## You probably want to run:
## docker-compose -f docker-compose.yml -f docker-compose.infogami-local.yml -f docker-compose.production.yml up -d
##

version: "3"
services:
  web:
    environment:
      - GUNICORN_OPTS= --workers 50 --timeout 300  # 5 minutes before reload
      - OL_CONFIG=/olsystem/etc/openlibrary.yml
      - PYENV_VERSION=3.8.6
    volumes:
      - ../olsystem:/olsystem
    command:
      - |
        ln -sfv /openlibrary/conf/nginx/sites-available/openlibrary.conf /etc/nginx/sites-available/
        && ln -sfv /etc/nginx/sites-available/openlibrary.conf /etc/nginx/sites-enabled/
        && systemctl start nginx
