# This file is applied "on top" of docker-compose.yml when docker-compose
# is used without the -f parameter. It contains local development specific
# configuration options which we don't want to apply to production/staging

version: "3.1"
services:
  web:
    ports:
      # Debugger
      - 3000:3000
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
  solr-updater:
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
  db:
    volumes:
      - .:/openlibrary
  covers:
    ports:
      - 7075:7075
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
  infobase:
    ports:
      - 7000:7000
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
  home:
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
volumes:
  ol-vendor:
