version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    working_dir: "/solr_builder"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - ".:/solr_builder"
      - "/storage:/storage"
    networks:
      - db-access

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080
    networks:
      - db-access

  solr:
    image: solr:8.8.2
    restart: on-failure
    environment:
      # This is optimized for bulk loading, but should be shortened for production
      # and we should set autoSoftCommit to a value that makes sense for our query usage (5-15 sec?)
      - SOLR_OPTS=-Dsolr.autoCommit.maxTime=3600000
      - SOLR_JAVA_MEM=-Xms3g -Xmx3g
    ports:
      - 8983:8983
    volumes:
      - solr-data:/var/solr/data
      - ../../conf/solr8-ol:/opt/solr/server/solr/configsets/olconfig:ro
    networks:
      - solr-access
    command: solr-precreate openlibrary /opt/solr/server/solr/configsets/olconfig

  # We need ability to use openlibrary code
  ol:
    image: olpython:latest
    build:
      context: ../..
      dockerfile: scripts/solr_builder/Dockerfile.olpython
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      # The above volume mounts are required so that the local dev bind mount below
      # does not clobber the data generated inside the image / container
      - "../../:/openlibrary"
    networks:
      - solr-access
      - db-access

volumes:
  postgres-data:
  solr-data:
  ol-vendor:

networks:
  db-access:
  solr-access:
