name: auto_unassigner
on:
  schedule:
    - cron: '0 16 * * 1'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  auto_unassigner:
    if: ${{ github.repository == 'internetarchive/openlibrary'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install @octokit/action
      - run: node scripts/gh_scripts/auto_unassigner.mjs --repoOwner "internetarchive" --daysSince 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ABC_TEAM_PLUS}}
