name: lint_python
on: [push]  # pull_request, 
jobs:
  lint_python:
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: sudo apt-get install libxml2-dev libxslt-dev
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install -r requirements_test.txt
      - run: pip list --outdated
      - run: git clone https://github.com/internetarchive/infogami.git vendor/infogami-master
      - run: rm infogami  # Remove symlink in favour of PYTHONPATH
      - run: make lint
      - run: make i18n
      - run: PYTHONPATH="$PYTHONPATH:$PWD/vendor/infogami-master" make test-py
      - run: PYTHONPATH="$PYTHONPATH:$PWD/vendor/infogami-master" source scripts/run_doctests.sh
