name: python_tests
on: [push]  # pull_request,
jobs:
  python_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.8]  # , 3.9]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: sudo apt-get install libxml2-dev libxslt-dev
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install -r requirements_test.txt
      - run: pip list --outdated
      - run: make git
      - if: matrix.python-version >= 3.0
        run: pushd vendor/infogami && git pull origin master && popd
      - run: make lint
      - run: make i18n
      - run: make test-py
      - run: source scripts/run_doctests.sh
