name: python_tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  python_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    runs-on: ubuntu-16.04  # Should match Dockerfile.olbase
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # https://lxml.de/installation.html#requirements
      - run: sudo apt-get install libxml2-dev libxslt-dev
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install -r requirements_test.txt
      - run: pip list --outdated
      - run: make lint-diff
      - run: make git
      - run: make i18n
      - run: pushd vendor/infogami && git pull origin master && popd
      - run: make lint
      - run: make test-py
      - run: source scripts/run_doctests.sh
