name: remove_labels
on:
  pull_request:
    types: [synchronize]
jobs:
  remove_on_testing_labels:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr edit $PR_NUM --remove-label "On testing.openlibrary.org","On ol-mek (http://ol-dev1.us.archive.org:1337)","On ol-jchamp" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.pull_request.number }}
